config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  
  get '/:slug', to: 'links#short', as: :short

  root 'links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  include Rails.application.routes.url_helpers

  # validation
  validates :url, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  # relationships
  belongs_to :user
  has_many :link_user
  has_many :link_user_history, through: :link_user, source: :user

  # soft delete
  acts_as_paranoid

  # auto slug generation
  before_validation :generate_slug

  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
  end

  def short
    # require 'uri'
    # uri = URI.parse(self.url)
    # uri = URI.parse("http://#{url}") if uri.scheme.nil?
    
    # return uri.scheme + "://" + uri.host.downcase + "/#{self.slug}"
    return "http://localhost:3000/#{self.slug}"
  end

end

app/models/link_user.rb
class LinkUser < ApplicationRecord
  belongs_to :link
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # relationships
  has_many :links
  has_many :link_user
  has_many :link_user_history, through: :link_user, source: :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :find_link, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]

  def index
    @links = Link.all
  end

  def show
    @histories = User.joins(:link_user).where(:link_user =>{link_id: @link.id}).select("email, clicked")
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to link_path(@link), notice: "Link was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to link_path(@link), notice: "Link was successfully updated."
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @link.destroy

    redirect_to links_path, notice: "Link was successfully destroyed."
  end

  def short
    @link = Link.find_by_slug(params[:slug]) 

    if @link.nil?
      render file: "#{Rails.root}/public/404.html", layout: false,  status: 400
    elsif
      @link.update({clicked: @link.clicked + 1})

      if LinkUser.exists?(user_id: current_user.id, link_id: @link.id)
        @link_user = LinkUser.find_by(user_id: current_user.id, link_id: @link.id)
        @link_user.update({clicked: @link_user.clicked + 1})
      else
        LinkUser.create!(user_id: current_user.id, link_id: @link.id, clicked: 1)
      end

      redirect_to @link.url
    end
  end

  private
  def find_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:url, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>

<div class="main flex-grow-1 p-0 ms-1">
  <div class="container container-breadcrumb ">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href=<%= root_path %>>首頁</a></li>
        <li class="breadcrumb-item active" aria-current="page">URL列表</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <%= link_to "New Link", new_link_path, class: "btn btn-outline-dark" %>
    <table class="table table-striped ">
      <thead>
        <tr>
          <th>Url</th>
          <th>Short URL</th>
          <th>Clicked</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @links.each do |link| %>
          <tr>
            <td><a href="<%= link.url %>"><%= link.url %></a></td>
            <td><a href="<%= link.short %>"><%= link.short %></a></td>
            <td><%= link.clicked %></td>
            <td><%= link_to 'Show', link %></td>
            <td><%= link_to 'Edit', edit_link_path(link) %></td>
            <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Short URL:</strong>
  <a href="<%= @link.short %>"><%= @link.short %></a>
</p>

<p>
  <strong>Clicked:</strong>
  <%= @link.clicked %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> | <%= link_to 'Back', links_path %>

<table class="table table-striped ">
  <thead>
    <tr>
      <th>Visitor Email</th>
      <th>Visitor Clicked</th>
    </tr>
  </thead>
  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.email %></td>
        <td><%= history.clicked %></td>
      </tr>
    <% end %>
  </tbody>
</table>